### ISSUE TITLE
How to output the best parameter values

### ISSUE THREAD

**Issue by liqi6811** [cerlymarco/keras-hypetune#1]
Hi Cerly, 

This package is great, but how to output the best parameter values? 

Thank you, 
Ling

**Comment by cerlymarco** [comment]
Hi, thanks

[Following the documentation](https://github.com/cerlymarco/keras-hypetune/blob/cbaea247716e02cc922657d8e7a3557e09832322/kerashypetune/kerashypetune.py#L196)

```
kgs = KerasGridSearch(...)
kgs.search(x_train, y_train, validation_data=(x_valid, y_valid))
kgs.best_params # <==============
```

You can also find full examples in the notebook folder

Don't forget to live a star to the project to support it ;-)
