### ISSUE TITLE
Multi-input functional model: ValueError inconsistent number of samples

### ISSUE THREAD

**Issue by ddenz** [cerlymarco/keras-hypetune#2]
Hi Marco,

This is a really great package, but I'm having trouble getting it to work. I have a model which takes text and audio features (numpy arrays) which I am passing to search, as with the Keras `fit()` method:

```
print(tf_train.shape, af_train.shape, y_train.shape)
kgs.search({'text_inputs': tf_train, 'audio_inputs': af_train}, {'labels': y_train})
```

I am getting the output and error below:

> (61, 400) (61, 400, 13) (61, 3)
> ...
> ValueError: Found input variables with inconsistent numbers of samples: [2, 1]

I have tried passing the features in a list and the labels as-is (this resembles your notebook example), but with the same error:

```
print(tf_train.shape, af_train.shape, y_train.shape)
kgs.search([tf_train, af_train], y_train)
```

> ValueError: Found input variables with inconsistent numbers of samples: [2, 61]

Any ideas?

Thanks!

André

**Comment by cerlymarco** [comment]
Hi,

do you have a reproducible example? does the model work making a simple fit with tf.keras?

thanks

**Comment by ddenz** [comment]
Sure here's one. There's a bit of info about my environment in the header.
Let me know if you'd like anything else. Thanks!

**Comment by ddenz** [comment]
Sure, [here](https://github.com/ddenz/asfmss/blob/main/example.py)'s one. There's a bit of info about my environment in the header. Let me know if you'd like anything else. Yes, a simple fit() works fine.

**Comment by cerlymarco** [comment]
Hi, you can solve it by installing the new version (0.1.3): pip install --upgrade keras-hypetune

[Here](https://colab.research.google.com/drive/1ONmy-SZQO9g2K0fbR_QPvrj-4YsUaVDK?usp=sharing) is your example.

If you support the project don't forget to leave a star
thanks
