### ISSUE TITLE
Sample weights

### ISSUE THREAD

**Issue by b-anthony-aguilar** [cerlymarco/keras-hypetune#3]
Hi, maybe this is not an issue but something I am missing. Is there a way to enter sample weights in the search? Any help would be appreciated. Thanks,

**Comment by cerlymarco** [comment]
Hi, 

`sample_weight` is not a tunable parameter.

you can use it as always inside your tuner class:

```
kgs = KerasGridSearch(...)
kgs.search(X, y, sample_weight=...)
```

If you support the project, don't forget to leave a star ;-)
