### ISSUE TITLE
ModuleNotFoundError: No module named 'keras_hypetune'

### ISSUE THREAD

**Issue by rproner1** [cerlymarco/keras-hypetune#4]
I'm having issues loading the package in my scripts. Is `keras_hypetune` the correct name to import under?

**Comment by cerlymarco** [comment]
Hi,

the correct way is, for example:

`from kerashypetune import KerasGridSearch`

You will find some examples in the [notebooks](https://github.com/cerlymarco/keras-hypetune/tree/master/notebooks) folder

Thanks
